# Generated by Django 5.0.3 on 2024-04-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rate',
            field=models.CharField(choices=[('G', 'General Audience'), ('P', 'Parental Guidance'), ('R', 'Restricted'), ('N', 'No one 17 and under admitted')], default='G', max_length=1),
        ),
    ]
