# Generated by Django 5.0.3 on 2024-04-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_anime_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('N', 'To watch'), ('F', 'Watching'), ('H', 'Half way!'), ('D', 'Done!')], default='N', max_length=1)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.anime')),
            ],
        ),
    ]
