# Generated by Django 5.0.3 on 2024-04-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_phasing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='Streamer',
            field=models.ManyToManyField(to='main_app.streamer'),
        ),
    ]
